omod TRANSFORM is 
  protecting QID .
  protecting NAT .

  subsort Qid < Oid .
  class Sender | buff : List, rec : Oid, cnt : Nat, ack-w : Bool .  
  class Receiver | buff : List, snd : Oid, cnt : Nat .
  msg to_from_val_cnt_ : Oid Oid Nat Nat -> Msg [ctor] .
  msg to_from_ack_ : Oid Oid Nat -> Msg [ctor] .

  vars N M : Nat . 
  var L : List . 
  vars A B : Oid . 
  var TV : Bool .

  rl [snd] : < A : Sender | buff: (N ; L),rec: B,cnt: M,ack-w: false > => < A : Sender | buff: L,rec: B,cnt: M,ack-w: true > .
  rl [rec] : < B : Receiver | buff: L,snd: A,cnt: M > => < B : Receiver | buff: (L ; N),snd: A,cnt: s(M) > .
  rl [ack-rec] : < A : Sender | buff: L, rec: B, cnt: M, ack-w: true > => < A : Sender | buff: L, rec: B, cnt: s(M), ack-w: false > .
endom